#!/bin/bash





module add jdk/8
module add mambaforge
mamba activate gemoma



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Phase 1: Preprocessing RNA-seq dat
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Extract introns (and coverage) running

java -jar <PATH>/bin/gemoma2.3/GeMoMa-1.9.jar CLI ERE \
m="<PATH>/<PATH>/Cardamine_RNASeq.sorted.bam"    # bam file was generated by Hisat2


# Optionally denoise the extracted introns running:

java -jar <PATH>/bin/gemoma2.3/GeMoMa-1.9.jar CLI DenoiseIntrons \
i="introns.gff" \
coverage_unstranded="coverage.bedgraph"



# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Phase 2: Prediction candidate transcripts
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# Extract CDS-parts (and proteins) of the reference organism 

for ANOTATION in *_genomic.gff; do
        echo $ANOTATION
        REFERENCE=${ANOTATION%_genomic.gff}_genomic.fna
        java -jar <PATH>/bin/gemoma2.3/GeMoMa-1.9.jar CLI Extractor \
        a=${ANOTATION} g=${REFERENCE} Ambiguity=AMBIGUOUS outdir=${ANOTATION%_genomic.gff}
done





# Find homologous parts in the target organism 
makeblastdb \
-dbtype nucl \
-hash_index \
-out blastdb \
-in C087_203_hap1.fa.masked.fa




# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# FOLLOWING TASKS WE RUN IN A SEPARATE SCRIPTS


# 2_GenomeAnnotation.GeMoMa.Phase2.1.sh

# 2_GenomeAnnotation.GeMoMa.Phase2.2.sh

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Phase 3: Aggregate and filter predictions
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# Aggregate predictions running:

java -jar <PATH>/bin/gemoma2.3/GeMoMa-1.9.jar CLI GAF \
p="CardamineHirsuta" g="CardamineHirsuta.carhr38/predicted_annotation.gff" \
p="ArabidopsisArenosa" g="ArabidopsisArenosa.GCA_905216605.1_AARE701a/predicted_annotation.gff" \
p="ArabidopsisThaliana" g="ArabidopsisThaliana.GCF_000001735.4_TAIR10.1/predicted_annotation.gff" \
p="BrassicaRapa" g="BrassicaRapa.GCF_000309985.2_CAAS_Brap_v3.01/predicted_annotation.gff" \
p="RaphanusSativus" g="RaphanusSativus.GCF_000801105.2_ASM80110v3/predicted_annotation.gff" \
p="BrassicaNapus" g="BrassicaNapus.GCF_020379485.1_Da-Ae/predicted_annotation.gff" \
p="ThlaspiArvense" g="ThlaspiArvense.GCA_911865555.2_T_arvense_v2/predicted_annotation.gff"






# Predict UTRs and rename predictions running:

java -jar <PATH>/bin/gemoma2.3/GeMoMa-1.9.jar CLI AnnotationFinalizer \
        g=C087_203_hap2.fa.masked.fasta \
        a=filtered_predictions.gff \
        rename=NO


