#!/bin/bash

# receive Nucleotide substitution model from IQ_TREE a parse it to RAxML-NG "format"


MODEL="$1"


MODEL="$(sed 's/K2P/K80/' <<<"$MODEL")"

MODEL="$(sed 's/TN/TN93/' <<<"$MODEL")"
MODEL="$(sed 's/TN93e/TN93ef/' <<<"$MODEL")" #  povodne v model bolo TNe, len predosly sed to zmenil na TN93e ;  TNe  je TN93ef
MODEL="$(sed 's/K3P/K81/' <<<"$MODEL")"
MODEL="$(sed 's/K81u/K81uf/' <<<"$MODEL")" #  to iste co vyssie
MODEL="$(sed 's/TPM2u/TPM2uf/' <<<"$MODEL")"
MODEL="$(sed 's/TPM3u/TPM3uf/' <<<"$MODEL")"

MODEL="$(sed 's/TIM+/TIM1uf+/' <<<"$MODEL")"
MODEL="$(sed 's/TIMe/TIM1/' <<<"$MODEL")" # opat to co vyssie, len naopak

MODEL="$(sed 's/TIM2/TIM2uf/' <<<"$MODEL")"
MODEL="$(sed 's/TIM2ufe/TIM2/' <<<"$MODEL")" # opat to co vyssie, len naopak

MODEL="$(sed 's/TIM3/TIM3uf/' <<<"$MODEL")"
MODEL="$(sed 's/TIM3ufe/TIM3/' <<<"$MODEL")" # opat to co vyssie, len naopak

MODEL="$(sed 's/TVMe/TVMef/' <<<"$MODEL")"  

echo "$MODEL" # odosli

exit




case $IQ_MODEL in
	JC)
		RAXML_MODEL="$IQ_MODEL"
		;;
	JC+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	JC+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	JC+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	JC+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	JC+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	F81+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	F81+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	F81+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	F81+F+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	F81+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	F81+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K2P)
		RAXML_MODEL="K80"
		;;
	K2P+I)
		RAXML_MODEL="K80+I"
		;;
	K2P+G4)
		RAXML_MODEL="K80+G4"
		;;
	K2P+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K2P+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K2P+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	HKY+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	HKY+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	HKY+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	HKY+F+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	HKY+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	HKY+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TNe)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TNe+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TNe+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TNe+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TNe+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TNe+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TN+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TN+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TN+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TN+F+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TN+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TN+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K3P)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K3P+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K3P+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K3P+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K3P+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K3P+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K3Pu+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K3Pu+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K3Pu+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K3Pu+F+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K3Pu+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	K3Pu+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM2+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM2+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM2+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM2+F+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM2+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM2+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM2u+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM2u+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM2u+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM2u+F+I+G4143.267)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM2u+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM2u+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM3+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM3+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM3+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM3+F+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM3+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM3+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM3u+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM3u+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM3u+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM3u+F+I+G4146.031)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM3u+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TPM3u+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIMe)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIMe+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIMe+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIMe+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIMe+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIMe+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM+F+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM2e)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM2e+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM2e+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM2e+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM2e+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM2e+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM2+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM2+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM2+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM2+F+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM2+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM2+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM3e)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM3e+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM3e+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM3e+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM3e+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM3e+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM3+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM3+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM3+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM3+F+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM3+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TIM3+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TVMe)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TVMe+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TVMe+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TVMe+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TVMe+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TVMe+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TVM+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TVM+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TVM+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TVM+F+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TVM+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	TVM+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	SYM)
		RAXML_MODEL="$IQ_MODEL"
		;;
	SYM+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	SYM+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	SYM+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	SYM+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	SYM+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;
	GTR+F)
		RAXML_MODEL="$IQ_MODEL"
		;;
	GTR+F+I)
		RAXML_MODEL="$IQ_MODEL"
		;;
	GTR+F+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	GTR+F+I+G4)
		RAXML_MODEL="$IQ_MODEL"
		;;
	GTR+F+R2)
		RAXML_MODEL="$IQ_MODEL"
		;;
	GTR+F+R3)
		RAXML_MODEL="$IQ_MODEL"
		;;

		
		
		
	*)
		echo "Sorry, I don't understand"
		;;
  esac



echo "$retval" # odosli
retval=$( testlock )  # prijmi
