#!/bin/bash


export ALIGNMENT    # PHYLIP format, without invariant sites
export MODEL        # raxml.bestModel file generated by previous script
export PBS_NUM_PPN  # number of CPU threads
export SEED=$(($RANDOM*$RANDOM))
export TREE         # integer, number of the tree. This script used to be submitted in 500 jobs, generating 500 trees in parallel


source /cvmfs/software.metacentrum.cz/modulefiles/5.1.0/loadmodules
module load raxml-ng/8


raxml-ng \
--msa "$ALIGNMENT" \
--model $MODEL \
--bootstrap \
--bs-trees 1 --blopt nr_safe --seed "$SEED" --threads $PBS_NUM_PPN --prefix "${ALIGNMENT%.*}"_"$MODEL"_"$TREE" >> "${ALIGNMENT%.*}"_"$TREE".log


exit


